version: 2.1

orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build:
    docker:
      - image: cimg/android:2022.09.2
    working_directory: ~/repo/shared-preferences-delegates
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./gradlew check
      - run: ./gradlew :core:testDebugUnitTestCoverage
      - run: ./gradlew :moshi:testDebugUnitTestCoverage
      - run: ./gradlew :serialization:testDebugUnitTestCoverage
      - codecov/upload:
          file: core/build/reports/jacoco/testDebugUnitTestCoverage/testDebugUnitTestCoverage.xml
      - codecov/upload:
          file: moshi/build/reports/jacoco/testDebugUnitTestCoverage/testDebugUnitTestCoverage.xml
      - codecov/upload:
          file: serialization/build/reports/jacoco/testDebugUnitTestCoverage/testDebugUnitTestCoverage.xml

workflows:
  test:
    jobs:
      - build
