version: 2.1

orbs:
  codecov: codecov/codecov@4.2.0

jobs:
  build:
    docker:
      - image: cimg/android:2024.10.1
    working_directory: ~/repo/shared-preferences-delegates
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: ./gradlew check
      - run: ./gradlew koverXmlReport
      - codecov/upload:
          file: build/reports/kover/report.xml

workflows:
  test:
    jobs:
      - build
