version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.17
    working_directory: ~/repo/shared-preferences-delegates
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - run: gradle check

workflows:
  test:
    jobs:
      - build
